### ISSUE TITLE
README Badge Error.

### ISSUE THREAD

**Issue by otnc** [Zyplos/discord-readme-badge#12]
![Screenshot 2024-05-30 11 55 54](https://github.com/Zyplos/discord-readme-badge/assets/116952822/1aca96b5-3081-45ee-9814-72ad13a663a3)

**Comment by otnc** [comment]
@Zyplos

**Comment by zyplos** [comment]
This is an old project of mine that I updated recently. Thank you for bringing this up.
Looking at some error logs, it seems the problem is I wasn't correctly handling how Discord's newest API version returns offline member presences. The card should correctly show that you're offline instead of giving you an error.

@otoneko1102 Let me know if this has been fixed.
